### ISSUE TITLE
【离谱级】sakura_bind_settings_cache清空选项后 依旧会给物品增加NBT 导致玩家原版合成书无法使用！

### ISSUE THREAD

**Issue by 8MiYile** [SakuraTown/SakuraBind#10]
我真的是服了你了，我禁用了他还能工作
我都不知道你这插件咋写的，我都以为禁用了我就能给玩家交代了，结果玩家还说用不了
一看物品信息才发现 又被添加了

**Comment by Iseason2000** [comment]
绑定物品是一定会有nbt的，清空sakura_bind_settings_cache并不能做到无NBT
如果你遇到nbt问题请不要绑定该物品

**Comment by 8MiYile** [comment]
但问题是 我插件装上去 啥都没增加 只禁用了那个选项 依旧给所有物品增加了这个NBT 包括木板之类的方块掉落物也加

**Comment by Iseason2000** [comment]
请检查下配置文件 `global-setting.yml` 此配置对所有物品生效
里面的 `auto-bind.enable` 是否为 `true`, 开启此项将**绑定所有物品**

如果需要绑定特定的物品需要到 `settings.yml`中配置匹配器并为匹配器设置配置

### 补救措施
* 方式一 
将 `global-setting.yml` 中的` auto-bind.enable` 设置为 `false`
并将 `auto-unbind.enable`、设置为true  并打开一个或多个解绑的方式, 比如 `auto-unbind.onScanner ` 
此方式将自动解绑所有绑定的物品

* 方式二
  通过命令 sakurabind unBindAll 玩家名称手动解绑玩家背包里的物品


如果你还有疑问可以进QQ群 887296263 获得实时的咨询
