### ISSUE TITLE
BUG提交

### ISSUE THREAD

**Issue by MERRYACS** [SakuraTown/SakuraBind#3]
1禁止绑定物品放入容器
 可以通过按键 1 2 3 4 5 6 7 8 9来绕过检测直接放入
2当玩家碰到地上的绑定物品时 会返还给物主 但是如果物主满包了则不会返还

**Comment by Iseason2000** [comment]
抱歉没有注意到issue
问题已在最新构建版中修复, https://github.com/SakuraTown/SakuraBind/suites/10511023655/artifacts/521857077
将在正式版2.0.5版本加入
