### ISSUE TITLE
openLast玩家不存在

### ISSUE THREAD

**Issue by zfms4188** [SakuraTown/SakuraBind#4]
使用指令openLast的时候 不能正常使用玩家名字打开

即使已经输入了名字了 还是会提示玩家不存在

**Comment by Iseason2000** [comment]
未能复现问题，请提供服务端版本，插件版本，以及测试的过程

![image](https://user-images.githubusercontent.com/65019366/231788522-8571612e-0df7-4ae0-ad3e-64a9862eb5de.png)

**Comment by Iseason2000** [comment]
该命令所指定的玩家需要登陆过该服务器，因为读取的是离线玩家的数据，如果是群组服可能出现该问题，解决办法是到登陆服输入命令
