### ISSUE TITLE
漏斗问题

### ISSUE THREAD

**Issue by zfms4188** [SakuraTown/SakuraBind#5]
将漏斗对准容器
把绑定物品放进漏斗里
物品并没有进入容器  而会直接消失 失物招领里也没有

**Comment by Iseason2000** [comment]
部分 mod 服务端本身的bug导致，无法修复，请不要使用该功能
将 `item-deny.container-move` 和  `item-deny.hopper `设置为false

![image](https://user-images.githubusercontent.com/65019366/231789122-4a663326-301b-4ace-866a-648edfc20b86.png)
