### ISSUE TITLE
1.21purpur端遇到问题无法启动

### ISSUE THREAD

**Issue by ximuya2** [SakuraTown/SakuraBind#9]
![image](https://github.com/user-attachments/assets/9669de7d-1ac8-458e-9077-3facab363eca)
如图

**Comment by Iseason2000** [comment]
由于 使用的 nbt 库暂未支持 1.21 所以本插件暂不支持 1.21 ，请加QQ群: 887296263 第一时间获得更新

**Comment by Iseason2000** [comment]
2.3.13 已支持1.21版本
